language: python
python: "3.6"

cache:
  directories:
    - $HOME/.cache/pip

services:
  - mysql

env:
  global:
    - DATABASE_URL="mysql://root:@localhost/poradnia"
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=py27-dj111-coveralls
    - TOX_ENV=py36-dj111-coveralls

matrix:
  allow_failures:
    - env: TOX_ENV=flake8

install:
  - pip install -U pip wheel
  - pip install tox
script:
  - .contrib/travis-ci/create-database.sh
  - tox -e $TOX_ENV

after_script:
- rm $HOME/.cache/pip/log/*
