version: '2.1'
# This is application’s services configuration for development purposes only.

services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "poradnia"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./.contrib/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql_db:/var/lib/mysql

  gulp:
    build:
      context: .
      dockerfile: .contrib/docker/Dockerfile.gulp
    working_dir: /app
    command: npx gulp build
    ports:
      - "35729:35729"
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: .contrib/docker/Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      DATABASE_URL: mysql://root:password@db/poradnia
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_db:
